    let listOfMatches = [
        {"homeTeam":"Palmeiras - SP","awayTeam":"Cuiab\u00e1 Saf - MT","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Am\u00e9rica Saf - MG","awayTeam":"Fluminense - RJ","homeScore":"0","awayScore":"3","done":true},
{"homeTeam":"Botafogo - RJ","awayTeam":"S\u00e3o Paulo - SP","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Athletico Paranaense - PR","awayTeam":"Goi\u00e1s - GO","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Red Bull Bragantino - SP","awayTeam":"Bahia - BA","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Fortaleza - CE","awayTeam":"Internacional - RS","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Atl\u00e9tico Mineiro Saf - MG","awayTeam":"Vasco da Gama S.a.f. - RJ","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Flamengo - RJ","awayTeam":"Coritiba S.a.f. - PR","homeScore":"3","awayScore":"0","done":true},
{"homeTeam":"Corinthians - SP","awayTeam":"Cruzeiro Saf - MG","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Gr\u00eamio - RS","awayTeam":"Santos - SP","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Fluminense - RJ","awayTeam":"Athletico Paranaense - PR","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Cuiab\u00e1 Saf - MT","awayTeam":"Red Bull Bragantino - SP","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"S\u00e3o Paulo - SP","awayTeam":"Am\u00e9rica Saf - MG","homeScore":"3","awayScore":"0","done":true},
{"homeTeam":"Cruzeiro Saf - MG","awayTeam":"Gr\u00eamio - RS","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Internacional - RS","awayTeam":"Flamengo - RJ","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Santos - SP","awayTeam":"Atl\u00e9tico Mineiro Saf - MG","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Vasco da Gama S.a.f. - RJ","awayTeam":"Palmeiras - SP","homeScore":"2","awayScore":"2","done":true},
{"homeTeam":"Coritiba S.a.f. - PR","awayTeam":"Fortaleza - CE","homeScore":"0","awayScore":"3","done":true},
{"homeTeam":"Goi\u00e1s - GO","awayTeam":"Corinthians - SP","homeScore":"3","awayScore":"1","done":true},
{"homeTeam":"Bahia - BA","awayTeam":"Botafogo - RJ","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Fortaleza - CE","awayTeam":"Fluminense - RJ","homeScore":"4","awayScore":"2","done":true},
{"homeTeam":"Coritiba S.a.f. - PR","awayTeam":"S\u00e3o Paulo - SP","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Palmeiras - SP","awayTeam":"Corinthians - SP","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Santos - SP","awayTeam":"Am\u00e9rica Saf - MG","homeScore":"3","awayScore":"2","done":true},
{"homeTeam":"Red Bull Bragantino - SP","awayTeam":"Cruzeiro Saf - MG","homeScore":"0","awayScore":"3","done":true},
{"homeTeam":"Atl\u00e9tico Mineiro Saf - MG","awayTeam":"Athletico Paranaense - PR","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Flamengo - RJ","awayTeam":"Botafogo - RJ","homeScore":"2","awayScore":"3","done":true},
{"homeTeam":"Cuiab\u00e1 Saf - MT","awayTeam":"Gr\u00eamio - RS","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Internacional - RS","awayTeam":"Goi\u00e1s - GO","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Vasco da Gama S.a.f. - RJ","awayTeam":"Bahia - BA","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Cruzeiro Saf - MG","awayTeam":"Santos - SP","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Fluminense - RJ","awayTeam":"Vasco da Gama S.a.f. - RJ","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Am\u00e9rica Saf - MG","awayTeam":"Cuiab\u00e1 Saf - MT","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Athletico Paranaense - PR","awayTeam":"Flamengo - RJ","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Bahia - BA","awayTeam":"Coritiba S.a.f. - PR","homeScore":"3","awayScore":"1","done":true},
{"homeTeam":"S\u00e3o Paulo - SP","awayTeam":"Internacional - RS","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Gr\u00eamio - RS","awayTeam":"Red Bull Bragantino - SP","homeScore":"3","awayScore":"3","done":true},
{"homeTeam":"Botafogo - RJ","awayTeam":"Atl\u00e9tico Mineiro Saf - MG","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Goi\u00e1s - GO","awayTeam":"Palmeiras - SP","homeScore":"0","awayScore":"5","done":true},
{"homeTeam":"Corinthians - SP","awayTeam":"Fortaleza - CE","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Santos - SP","awayTeam":"Bahia - BA","homeScore":"3","awayScore":"0","done":true},
{"homeTeam":"Red Bull Bragantino - SP","awayTeam":"Am\u00e9rica Saf - MG","homeScore":"2","awayScore":"2","done":true},
{"homeTeam":"Internacional - RS","awayTeam":"Athletico Paranaense - PR","homeScore":"0","awayScore":"2","done":true},
{"homeTeam":"Flamengo - RJ","awayTeam":"Goi\u00e1s - GO","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Cuiab\u00e1 Saf - MT","awayTeam":"Atl\u00e9tico Mineiro Saf - MG","homeScore":"0","awayScore":"4","done":true},
{"homeTeam":"Palmeiras - SP","awayTeam":"Gr\u00eamio - RS","homeScore":"4","awayScore":"1","done":true},
{"homeTeam":"Cruzeiro Saf - MG","awayTeam":"Fluminense - RJ","homeScore":"0","awayScore":"2","done":true},
{"homeTeam":"Coritiba S.a.f. - PR","awayTeam":"Vasco da Gama S.a.f. - RJ","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Botafogo - RJ","awayTeam":"Corinthians - SP","homeScore":"3","awayScore":"0","done":true},
{"homeTeam":"Fortaleza - CE","awayTeam":"S\u00e3o Paulo - SP","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Bahia - BA","awayTeam":"Flamengo - RJ","homeScore":"2","awayScore":"3","done":true},
{"homeTeam":"Fluminense - RJ","awayTeam":"Cuiab\u00e1 Saf - MT","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Palmeiras - SP","awayTeam":"Red Bull Bragantino - SP","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Atl\u00e9tico Mineiro Saf - MG","awayTeam":"Internacional - RS","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Gr\u00eamio - RS","awayTeam":"Fortaleza - CE","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Vasco da Gama S.a.f. - RJ","awayTeam":"Santos - SP","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Corinthians - SP","awayTeam":"S\u00e3o Paulo - SP","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Goi\u00e1s - GO","awayTeam":"Botafogo - RJ","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Athletico Paranaense - PR","awayTeam":"Coritiba S.a.f. - PR","homeScore":"3","awayScore":"2","done":true},
{"homeTeam":"Am\u00e9rica Saf - MG","awayTeam":"Cruzeiro Saf - MG","homeScore":"0","awayScore":"4","done":true},
{"homeTeam":"Bahia - BA","awayTeam":"Goi\u00e1s - GO","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Coritiba S.a.f. - PR","awayTeam":"Atl\u00e9tico Mineiro Saf - MG","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Botafogo - RJ","awayTeam":"Fluminense - RJ","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"S\u00e3o Paulo - SP","awayTeam":"Vasco da Gama S.a.f. - RJ","homeScore":"4","awayScore":"2","done":true},
{"homeTeam":"Am\u00e9rica Saf - MG","awayTeam":"Fortaleza - CE","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Red Bull Bragantino - SP","awayTeam":"Athletico Paranaense - PR","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Santos - SP","awayTeam":"Palmeiras - SP","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Flamengo - RJ","awayTeam":"Corinthians - SP","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Gr\u00eamio - RS","awayTeam":"Internacional - RS","homeScore":"3","awayScore":"1","done":true},
{"homeTeam":"Cruzeiro Saf - MG","awayTeam":"Cuiab\u00e1 Saf - MT","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Athletico Paranaense - PR","awayTeam":"Gr\u00eamio - RS","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Fortaleza - CE","awayTeam":"Vasco da Gama S.a.f. - RJ","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Flamengo - RJ","awayTeam":"Cruzeiro Saf - MG","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Cuiab\u00e1 Saf - MT","awayTeam":"Coritiba S.a.f. - PR","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"S\u00e3o Paulo - SP","awayTeam":"Goi\u00e1s - GO","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Internacional - RS","awayTeam":"Bahia - BA","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Corinthians - SP","awayTeam":"Fluminense - RJ","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Atl\u00e9tico Mineiro Saf - MG","awayTeam":"Palmeiras - SP","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Red Bull Bragantino - SP","awayTeam":"Santos - SP","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Botafogo - RJ","awayTeam":"Am\u00e9rica Saf - MG","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Fortaleza - CE","awayTeam":"Bahia - BA","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Cruzeiro Saf - MG","awayTeam":"Atl\u00e9tico Mineiro Saf - MG","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Am\u00e9rica Saf - MG","awayTeam":"Corinthians - SP","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Athletico Paranaense - PR","awayTeam":"Botafogo - RJ","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Santos - SP","awayTeam":"Internacional - RS","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Gr\u00eamio - RS","awayTeam":"S\u00e3o Paulo - SP","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Fluminense - RJ","awayTeam":"Red Bull Bragantino - SP","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Goi\u00e1s - GO","awayTeam":"Cuiab\u00e1 Saf - MT","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Palmeiras - SP","awayTeam":"Coritiba S.a.f. - PR","homeScore":"3","awayScore":"1","done":true},
{"homeTeam":"Vasco da Gama S.a.f. - RJ","awayTeam":"Flamengo - RJ","homeScore":"1","awayScore":"4","done":true},
{"homeTeam":"Coritiba S.a.f. - PR","awayTeam":"Santos - SP","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Bahia - BA","awayTeam":"Cruzeiro Saf - MG","homeScore":"2","awayScore":"2","done":true},
{"homeTeam":"Atl\u00e9tico Mineiro Saf - MG","awayTeam":"Red Bull Bragantino - SP","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Corinthians - SP","awayTeam":"Cuiab\u00e1 Saf - MT","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Botafogo - RJ","awayTeam":"Fortaleza - CE","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Am\u00e9rica Saf - MG","awayTeam":"Athletico Paranaense - PR","homeScore":"2","awayScore":"2","done":true},
{"homeTeam":"Internacional - RS","awayTeam":"Vasco da Gama S.a.f. - RJ","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"S\u00e3o Paulo - SP","awayTeam":"Palmeiras - SP","homeScore":"0","awayScore":"2","done":true},
{"homeTeam":"Goi\u00e1s - GO","awayTeam":"Fluminense - RJ","homeScore":"2","awayScore":"2","done":true},
{"homeTeam":"Flamengo - RJ","awayTeam":"Gr\u00eamio - RS","homeScore":"3","awayScore":"0","done":true},
{"homeTeam":"S\u00e3o Paulo - SP","awayTeam":"Athletico Paranaense - PR","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Cruzeiro Saf - MG","awayTeam":"Fortaleza - CE","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Santos - SP","awayTeam":"Corinthians - SP","homeScore":"0","awayScore":"2","done":true},
{"homeTeam":"Bahia - BA","awayTeam":"Palmeiras - SP","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Fluminense - RJ","awayTeam":"Atl\u00e9tico Mineiro Saf - MG","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Gr\u00eamio - RS","awayTeam":"Am\u00e9rica Saf - MG","homeScore":"3","awayScore":"1","done":true},
{"homeTeam":"Cuiab\u00e1 Saf - MT","awayTeam":"Botafogo - RJ","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Coritiba S.a.f. - PR","awayTeam":"Internacional - RS","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Vasco da Gama S.a.f. - RJ","awayTeam":"Goi\u00e1s - GO","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Red Bull Bragantino - SP","awayTeam":"Flamengo - RJ","homeScore":"4","awayScore":"0","done":true},
{"homeTeam":"Athletico Paranaense - PR","awayTeam":"Corinthians - SP","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Fluminense - RJ","awayTeam":"Bahia - BA","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Fortaleza - CE","awayTeam":"Atl\u00e9tico Mineiro Saf - MG","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Cruzeiro Saf - MG","awayTeam":"S\u00e3o Paulo - SP","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Gr\u00eamio - RS","awayTeam":"Coritiba S.a.f. - PR","homeScore":"5","awayScore":"1","done":true},
{"homeTeam":"Palmeiras - SP","awayTeam":"Botafogo - RJ","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Am\u00e9rica Saf - MG","awayTeam":"Internacional - RS","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Red Bull Bragantino - SP","awayTeam":"Goi\u00e1s - GO","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Santos - SP","awayTeam":"Flamengo - RJ","homeScore":"2","awayScore":"3","done":true},
{"homeTeam":"Vasco da Gama S.a.f. - RJ","awayTeam":"Cuiab\u00e1 Saf - MT","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"S\u00e3o Paulo - SP","awayTeam":"Fluminense - RJ","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Flamengo - RJ","awayTeam":"Fortaleza - CE","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Bahia - BA","awayTeam":"Gr\u00eamio - RS","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Internacional - RS","awayTeam":"Cruzeiro Saf - MG","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Corinthians - SP","awayTeam":"Red Bull Bragantino - SP","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Athletico Paranaense - PR","awayTeam":"Palmeiras - SP","homeScore":"2","awayScore":"2","done":true},
{"homeTeam":"Botafogo - RJ","awayTeam":"Vasco da Gama S.a.f. - RJ","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Atl\u00e9tico Mineiro Saf - MG","awayTeam":"Am\u00e9rica Saf - MG","homeScore":"2","awayScore":"2","done":true},
{"homeTeam":"Cuiab\u00e1 Saf - MT","awayTeam":"Santos - SP","homeScore":"3","awayScore":"0","done":true},
{"homeTeam":"Goi\u00e1s - GO","awayTeam":"Coritiba S.a.f. - PR","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Vasco da Gama S.a.f. - RJ","awayTeam":"Cruzeiro Saf - MG","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Cuiab\u00e1 Saf - MT","awayTeam":"Bahia - BA","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Atl\u00e9tico Mineiro Saf - MG","awayTeam":"Corinthians - SP","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Coritiba S.a.f. - PR","awayTeam":"Am\u00e9rica Saf - MG","homeScore":"3","awayScore":"1","done":true},
{"homeTeam":"Palmeiras - SP","awayTeam":"Flamengo - RJ","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Santos - SP","awayTeam":"Goi\u00e1s - GO","homeScore":"4","awayScore":"3","done":true},
{"homeTeam":"Red Bull Bragantino - SP","awayTeam":"S\u00e3o Paulo - SP","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Fluminense - RJ","awayTeam":"Internacional - RS","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Gr\u00eamio - RS","awayTeam":"Botafogo - RJ","homeScore":"0","awayScore":"2","done":true},
{"homeTeam":"Fortaleza - CE","awayTeam":"Athletico Paranaense - PR","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Botafogo - RJ","awayTeam":"Red Bull Bragantino - SP","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Cruzeiro Saf - MG","awayTeam":"Coritiba S.a.f. - PR","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Fortaleza - CE","awayTeam":"Cuiab\u00e1 Saf - MT","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"S\u00e3o Paulo - SP","awayTeam":"Santos - SP","homeScore":"4","awayScore":"1","done":true},
{"homeTeam":"Fluminense - RJ","awayTeam":"Flamengo - RJ","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Internacional - RS","awayTeam":"Palmeiras - SP","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Athletico Paranaense - PR","awayTeam":"Bahia - BA","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Goi\u00e1s - GO","awayTeam":"Atl\u00e9tico Mineiro Saf - MG","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Corinthians - SP","awayTeam":"Gr\u00eamio - RS","homeScore":"4","awayScore":"4","done":true},
{"homeTeam":"Am\u00e9rica Saf - MG","awayTeam":"Vasco da Gama S.a.f. - RJ","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Flamengo - RJ","awayTeam":"Am\u00e9rica Saf - MG","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Palmeiras - SP","awayTeam":"Fortaleza - CE","homeScore":"3","awayScore":"1","done":true},
{"homeTeam":"Cuiab\u00e1 Saf - MT","awayTeam":"S\u00e3o Paulo - SP","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Bahia - BA","awayTeam":"Corinthians - SP","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Gr\u00eamio - RS","awayTeam":"Atl\u00e9tico Mineiro Saf - MG","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Santos - SP","awayTeam":"Botafogo - RJ","homeScore":"2","awayScore":"2","done":true},
{"homeTeam":"Red Bull Bragantino - SP","awayTeam":"Internacional - RS","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Cruzeiro Saf - MG","awayTeam":"Goi\u00e1s - GO","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Vasco da Gama S.a.f. - RJ","awayTeam":"Athletico Paranaense - PR","homeScore":"0","awayScore":"2","done":true},
{"homeTeam":"Coritiba S.a.f. - PR","awayTeam":"Fluminense - RJ","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Internacional - RS","awayTeam":"Cuiab\u00e1 Saf - MT","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Athletico Paranaense - PR","awayTeam":"Cruzeiro Saf - MG","homeScore":"3","awayScore":"3","done":true},
{"homeTeam":"Fluminense - RJ","awayTeam":"Santos - SP","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Corinthians - SP","awayTeam":"Vasco da Gama S.a.f. - RJ","homeScore":"3","awayScore":"1","done":true},
{"homeTeam":"Fortaleza - CE","awayTeam":"Red Bull Bragantino - SP","homeScore":"0","awayScore":"3","done":true},
{"homeTeam":"Atl\u00e9tico Mineiro Saf - MG","awayTeam":"Flamengo - RJ","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"S\u00e3o Paulo - SP","awayTeam":"Bahia - BA","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Am\u00e9rica Saf - MG","awayTeam":"Palmeiras - SP","homeScore":"1","awayScore":"4","done":true},
{"homeTeam":"Botafogo - RJ","awayTeam":"Coritiba S.a.f. - PR","homeScore":"4","awayScore":"1","done":true},
{"homeTeam":"Goi\u00e1s - GO","awayTeam":"Gr\u00eamio - RS","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Santos - SP","awayTeam":"Athletico Paranaense - PR","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Internacional - RS","awayTeam":"Corinthians - SP","homeScore":"2","awayScore":"2","done":true},
{"homeTeam":"Goi\u00e1s - GO","awayTeam":"Fortaleza - CE","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Fluminense - RJ","awayTeam":"Palmeiras - SP","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Vasco da Gama S.a.f. - RJ","awayTeam":"Gr\u00eamio - RS","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"S\u00e3o Paulo - SP","awayTeam":"Atl\u00e9tico Mineiro Saf - MG","homeScore":"0","awayScore":"2","done":true},
{"homeTeam":"Bahia - BA","awayTeam":"Am\u00e9rica Saf - MG","homeScore":"3","awayScore":"1","done":true},
{"homeTeam":"Coritiba S.a.f. - PR","awayTeam":"Red Bull Bragantino - SP","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Cruzeiro Saf - MG","awayTeam":"Botafogo - RJ","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Cuiab\u00e1 Saf - MT","awayTeam":"Flamengo - RJ","homeScore":"3","awayScore":"0","done":true},
{"homeTeam":"Botafogo - RJ","awayTeam":"Internacional - RS","homeScore":"3","awayScore":"1","done":true},
{"homeTeam":"Atl\u00e9tico Mineiro Saf - MG","awayTeam":"Bahia - BA","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Corinthians - SP","awayTeam":"Coritiba S.a.f. - PR","homeScore":"3","awayScore":"1","done":true},
{"homeTeam":"Gr\u00eamio - RS","awayTeam":"Fluminense - RJ","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Am\u00e9rica Saf - MG","awayTeam":"Goi\u00e1s - GO","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Flamengo - RJ","awayTeam":"S\u00e3o Paulo - SP","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Fortaleza - CE","awayTeam":"Santos - SP","homeScore":"4","awayScore":"0","done":true},
{"homeTeam":"Palmeiras - SP","awayTeam":"Cruzeiro Saf - MG","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Red Bull Bragantino - SP","awayTeam":"Vasco da Gama S.a.f. - RJ","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Athletico Paranaense - PR","awayTeam":"Cuiab\u00e1 Saf - MT","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"S\u00e3o Paulo - SP","awayTeam":"Botafogo - RJ","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Internacional - RS","awayTeam":"Fortaleza - CE","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Cuiab\u00e1 Saf - MT","awayTeam":"Palmeiras - SP","homeScore":"0","awayScore":"2","done":true},
{"homeTeam":"Fluminense - RJ","awayTeam":"Am\u00e9rica Saf - MG","homeScore":"3","awayScore":"1","done":true},
{"homeTeam":"Cruzeiro Saf - MG","awayTeam":"Corinthians - SP","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Vasco da Gama S.a.f. - RJ","awayTeam":"Atl\u00e9tico Mineiro Saf - MG","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Santos - SP","awayTeam":"Gr\u00eamio - RS","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Coritiba S.a.f. - PR","awayTeam":"Flamengo - RJ","homeScore":"2","awayScore":"3","done":true},
{"homeTeam":"Bahia - BA","awayTeam":"Red Bull Bragantino - SP","homeScore":"4","awayScore":"0","done":true},
{"homeTeam":"Goi\u00e1s - GO","awayTeam":"Athletico Paranaense - PR","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Flamengo - RJ","awayTeam":"Internacional - RS","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Corinthians - SP","awayTeam":"Goi\u00e1s - GO","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Red Bull Bragantino - SP","awayTeam":"Cuiab\u00e1 Saf - MT","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Am\u00e9rica Saf - MG","awayTeam":"S\u00e3o Paulo - SP","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Botafogo - RJ","awayTeam":"Bahia - BA","homeScore":"3","awayScore":"0","done":true},
{"homeTeam":"Atl\u00e9tico Mineiro Saf - MG","awayTeam":"Santos - SP","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Athletico Paranaense - PR","awayTeam":"Fluminense - RJ","homeScore":"2","awayScore":"2","done":true},
{"homeTeam":"Fortaleza - CE","awayTeam":"Coritiba S.a.f. - PR","homeScore":"3","awayScore":"1","done":true},
{"homeTeam":"Palmeiras - SP","awayTeam":"Vasco da Gama S.a.f. - RJ","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Gr\u00eamio - RS","awayTeam":"Cruzeiro Saf - MG","homeScore":"3","awayScore":"0","done":true},
{"homeTeam":"Goi\u00e1s - GO","awayTeam":"Internacional - RS","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Athletico Paranaense - PR","awayTeam":"Atl\u00e9tico Mineiro Saf - MG","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Botafogo - RJ","awayTeam":"Flamengo - RJ","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Gr\u00eamio - RS","awayTeam":"Cuiab\u00e1 Saf - MT","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Fluminense - RJ","awayTeam":"Fortaleza - CE","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Corinthians - SP","awayTeam":"Palmeiras - SP","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Cruzeiro Saf - MG","awayTeam":"Red Bull Bragantino - SP","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Bahia - BA","awayTeam":"Vasco da Gama S.a.f. - RJ","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Am\u00e9rica Saf - MG","awayTeam":"Santos - SP","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"S\u00e3o Paulo - SP","awayTeam":"Coritiba S.a.f. - PR","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Flamengo - RJ","awayTeam":"Athletico Paranaense - PR","homeScore":"0","awayScore":"3","done":true},
{"homeTeam":"Internacional - RS","awayTeam":"S\u00e3o Paulo - SP","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Santos - SP","awayTeam":"Cruzeiro Saf - MG","homeScore":"0","awayScore":"3","done":true},
{"homeTeam":"Fortaleza - CE","awayTeam":"Corinthians - SP","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Coritiba S.a.f. - PR","awayTeam":"Bahia - BA","homeScore":"2","awayScore":"4","done":true},
{"homeTeam":"Red Bull Bragantino - SP","awayTeam":"Gr\u00eamio - RS","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Cuiab\u00e1 Saf - MT","awayTeam":"Am\u00e9rica Saf - MG","homeScore":"2","awayScore":"2","done":true},
{"homeTeam":"Palmeiras - SP","awayTeam":"Goi\u00e1s - GO","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Vasco da Gama S.a.f. - RJ","awayTeam":"Fluminense - RJ","homeScore":"4","awayScore":"2","done":true},
{"homeTeam":"Atl\u00e9tico Mineiro Saf - MG","awayTeam":"Botafogo - RJ","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Bahia - BA","awayTeam":"Santos - SP","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Am\u00e9rica Saf - MG","awayTeam":"Red Bull Bragantino - SP","homeScore":"0","awayScore":"2","done":true},
{"homeTeam":"Goi\u00e1s - GO","awayTeam":"Flamengo - RJ","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Fluminense - RJ","awayTeam":"Cruzeiro Saf - MG","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"S\u00e3o Paulo - SP","awayTeam":"Fortaleza - CE","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Vasco da Gama S.a.f. - RJ","awayTeam":"Coritiba S.a.f. - PR","homeScore":"5","awayScore":"1","done":true},
{"homeTeam":"Athletico Paranaense - PR","awayTeam":"Internacional - RS","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Gr\u00eamio - RS","awayTeam":"Palmeiras - SP","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Corinthians - SP","awayTeam":"Botafogo - RJ","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Atl\u00e9tico Mineiro Saf - MG","awayTeam":"Cuiab\u00e1 Saf - MT","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Flamengo - RJ","awayTeam":"Bahia - BA","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Fortaleza - CE","awayTeam":"Gr\u00eamio - RS","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Cuiab\u00e1 Saf - MT","awayTeam":"Fluminense - RJ","homeScore":"3","awayScore":"0","done":true},
{"homeTeam":"S\u00e3o Paulo - SP","awayTeam":"Corinthians - SP","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Internacional - RS","awayTeam":"Atl\u00e9tico Mineiro Saf - MG","homeScore":"0","awayScore":"2","done":true},
{"homeTeam":"Coritiba S.a.f. - PR","awayTeam":"Athletico Paranaense - PR","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Cruzeiro Saf - MG","awayTeam":"Am\u00e9rica Saf - MG","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Santos - SP","awayTeam":"Vasco da Gama S.a.f. - RJ","homeScore":"4","awayScore":"1","done":true},
{"homeTeam":"Red Bull Bragantino - SP","awayTeam":"Palmeiras - SP","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Botafogo - RJ","awayTeam":"Goi\u00e1s - GO","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Goi\u00e1s - GO","awayTeam":"Bahia - BA","homeScore":"4","awayScore":"6","done":true},
{"homeTeam":"Vasco da Gama S.a.f. - RJ","awayTeam":"S\u00e3o Paulo - SP","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Corinthians - SP","awayTeam":"Flamengo - RJ","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Internacional - RS","awayTeam":"Gr\u00eamio - RS","homeScore":"3","awayScore":"2","done":true},
{"homeTeam":"Fluminense - RJ","awayTeam":"Botafogo - RJ","homeScore":"0","awayScore":"2","done":true},
{"homeTeam":"Palmeiras - SP","awayTeam":"Santos - SP","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Fortaleza - CE","awayTeam":"Am\u00e9rica Saf - MG","homeScore":"3","awayScore":"2","done":true},
{"homeTeam":"Atl\u00e9tico Mineiro Saf - MG","awayTeam":"Coritiba S.a.f. - PR","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Athletico Paranaense - PR","awayTeam":"Red Bull Bragantino - SP","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Cuiab\u00e1 Saf - MT","awayTeam":"Cruzeiro Saf - MG","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Gr\u00eamio - RS","awayTeam":"Athletico Paranaense - PR","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Coritiba S.a.f. - PR","awayTeam":"Cuiab\u00e1 Saf - MT","homeScore":"0","awayScore":"3","done":true},
{"homeTeam":"Am\u00e9rica Saf - MG","awayTeam":"Botafogo - RJ","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Vasco da Gama S.a.f. - RJ","awayTeam":"Fortaleza - CE","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Goi\u00e1s - GO","awayTeam":"S\u00e3o Paulo - SP","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Bahia - BA","awayTeam":"Internacional - RS","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Palmeiras - SP","awayTeam":"Atl\u00e9tico Mineiro Saf - MG","homeScore":"0","awayScore":"2","done":true},
{"homeTeam":"Cruzeiro Saf - MG","awayTeam":"Flamengo - RJ","homeScore":"0","awayScore":"2","done":true},
{"homeTeam":"Santos - SP","awayTeam":"Red Bull Bragantino - SP","homeScore":"1","awayScore":"3","done":true},
{"homeTeam":"Fluminense - RJ","awayTeam":"Corinthians - SP","homeScore":"3","awayScore":"3","done":true},
{"homeTeam":"Bahia - BA","awayTeam":"Fortaleza - CE","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Cuiab\u00e1 Saf - MT","awayTeam":"Goi\u00e1s - GO","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"S\u00e3o Paulo - SP","awayTeam":"Gr\u00eamio - RS","homeScore":"3","awayScore":"0","done":true},
{"homeTeam":"Botafogo - RJ","awayTeam":"Athletico Paranaense - PR","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Atl\u00e9tico Mineiro Saf - MG","awayTeam":"Cruzeiro Saf - MG","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Internacional - RS","awayTeam":"Santos - SP","homeScore":"7","awayScore":"1","done":true},
{"homeTeam":"Flamengo - RJ","awayTeam":"Vasco da Gama S.a.f. - RJ","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Red Bull Bragantino - SP","awayTeam":"Fluminense - RJ","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Coritiba S.a.f. - PR","awayTeam":"Palmeiras - SP","homeScore":"0","awayScore":"2","done":true},
{"homeTeam":"Corinthians - SP","awayTeam":"Am\u00e9rica Saf - MG","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Fluminense - RJ","awayTeam":"Goi\u00e1s - GO","homeScore":"5","awayScore":"3","done":true},
{"homeTeam":"Athletico Paranaense - PR","awayTeam":"Am\u00e9rica Saf - MG","homeScore":"3","awayScore":"2","done":true},
{"homeTeam":"Red Bull Bragantino - SP","awayTeam":"Atl\u00e9tico Mineiro Saf - MG","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Palmeiras - SP","awayTeam":"S\u00e3o Paulo - SP","homeScore":"5","awayScore":"0","done":true},
{"homeTeam":"Cruzeiro Saf - MG","awayTeam":"Bahia - BA","homeScore":"3","awayScore":"0","done":true},
{"homeTeam":"Cuiab\u00e1 Saf - MT","awayTeam":"Corinthians - SP","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Gr\u00eamio - RS","awayTeam":"Flamengo - RJ","homeScore":"3","awayScore":"2","done":true},
{"homeTeam":"Vasco da Gama S.a.f. - RJ","awayTeam":"Internacional - RS","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Santos - SP","awayTeam":"Coritiba S.a.f. - PR","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Fortaleza - CE","awayTeam":"Botafogo - RJ","homeScore":"2","awayScore":"2","done":true},
{"homeTeam":"Am\u00e9rica Saf - MG","awayTeam":"Gr\u00eamio - RS","homeScore":"3","awayScore":"4","done":true},
{"homeTeam":"Palmeiras - SP","awayTeam":"Bahia - BA","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Atl\u00e9tico Mineiro Saf - MG","awayTeam":"Fluminense - RJ","homeScore":"2","awayScore":"0","done":true},
{"homeTeam":"Goi\u00e1s - GO","awayTeam":"Vasco da Gama S.a.f. - RJ","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Athletico Paranaense - PR","awayTeam":"S\u00e3o Paulo - SP","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Corinthians - SP","awayTeam":"Santos - SP","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Internacional - RS","awayTeam":"Coritiba S.a.f. - PR","homeScore":"3","awayScore":"4","done":true},
{"homeTeam":"Botafogo - RJ","awayTeam":"Cuiab\u00e1 Saf - MT","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Fortaleza - CE","awayTeam":"Cruzeiro Saf - MG","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Flamengo - RJ","awayTeam":"Red Bull Bragantino - SP","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Bahia - BA","awayTeam":"Fluminense - RJ","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Corinthians - SP","awayTeam":"Athletico Paranaense - PR","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Internacional - RS","awayTeam":"Am\u00e9rica Saf - MG","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Flamengo - RJ","awayTeam":"Santos - SP","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Coritiba S.a.f. - PR","awayTeam":"Gr\u00eamio - RS","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Atl\u00e9tico Mineiro Saf - MG","awayTeam":"Fortaleza - CE","homeScore":"3","awayScore":"1","done":true},
{"homeTeam":"Botafogo - RJ","awayTeam":"Palmeiras - SP","homeScore":"3","awayScore":"4","done":true},
{"homeTeam":"Cuiab\u00e1 Saf - MT","awayTeam":"Vasco da Gama S.a.f. - RJ","homeScore":"0","awayScore":"2","done":true},
{"homeTeam":"Goi\u00e1s - GO","awayTeam":"Red Bull Bragantino - SP","homeScore":"0","awayScore":"2","done":true},
{"homeTeam":"S\u00e3o Paulo - SP","awayTeam":"Cruzeiro Saf - MG","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Am\u00e9rica Saf - MG","awayTeam":"Atl\u00e9tico Mineiro Saf - MG","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Gr\u00eamio - RS","awayTeam":"Bahia - BA","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Palmeiras - SP","awayTeam":"Athletico Paranaense - PR","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Red Bull Bragantino - SP","awayTeam":"Corinthians - SP","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Cruzeiro Saf - MG","awayTeam":"Internacional - RS","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Fortaleza - CE","awayTeam":"Flamengo - RJ","homeScore":"0","awayScore":"2","done":true},
{"homeTeam":"Coritiba S.a.f. - PR","awayTeam":"Goi\u00e1s - GO","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Vasco da Gama S.a.f. - RJ","awayTeam":"Botafogo - RJ","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Santos - SP","awayTeam":"Cuiab\u00e1 Saf - MT","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Fluminense - RJ","awayTeam":"S\u00e3o Paulo - SP","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Am\u00e9rica Saf - MG","awayTeam":"Coritiba S.a.f. - PR","homeScore":"0","awayScore":"3","done":true},
{"homeTeam":"Internacional - RS","awayTeam":"Fluminense - RJ","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Athletico Paranaense - PR","awayTeam":"Fortaleza - CE","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"S\u00e3o Paulo - SP","awayTeam":"Red Bull Bragantino - SP","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Flamengo - RJ","awayTeam":"Palmeiras - SP","homeScore":"3","awayScore":"0","done":true},
{"homeTeam":"Corinthians - SP","awayTeam":"Atl\u00e9tico Mineiro Saf - MG","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Goi\u00e1s - GO","awayTeam":"Santos - SP","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Bahia - BA","awayTeam":"Cuiab\u00e1 Saf - MT","homeScore":"0","awayScore":"3","done":true},
{"homeTeam":"Botafogo - RJ","awayTeam":"Gr\u00eamio - RS","homeScore":"3","awayScore":"4","done":true},
{"homeTeam":"Cruzeiro Saf - MG","awayTeam":"Vasco da Gama S.a.f. - RJ","homeScore":"2","awayScore":"2","done":true},
{"homeTeam":"Coritiba S.a.f. - PR","awayTeam":"Cruzeiro Saf - MG","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Flamengo - RJ","awayTeam":"Fluminense - RJ","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Palmeiras - SP","awayTeam":"Internacional - RS","homeScore":"3","awayScore":"0","done":true},
{"homeTeam":"Gr\u00eamio - RS","awayTeam":"Corinthians - SP","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Red Bull Bragantino - SP","awayTeam":"Botafogo - RJ","homeScore":"2","awayScore":"2","done":true},
{"homeTeam":"Bahia - BA","awayTeam":"Athletico Paranaense - PR","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Cuiab\u00e1 Saf - MT","awayTeam":"Fortaleza - CE","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Atl\u00e9tico Mineiro Saf - MG","awayTeam":"Goi\u00e1s - GO","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Santos - SP","awayTeam":"S\u00e3o Paulo - SP","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Vasco da Gama S.a.f. - RJ","awayTeam":"Am\u00e9rica Saf - MG","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Corinthians - SP","awayTeam":"Bahia - BA","homeScore":"1","awayScore":"5","done":true},
{"homeTeam":"Athletico Paranaense - PR","awayTeam":"Vasco da Gama S.a.f. - RJ","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Fluminense - RJ","awayTeam":"Coritiba S.a.f. - PR","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Botafogo - RJ","awayTeam":"Santos - SP","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Atl\u00e9tico Mineiro Saf - MG","awayTeam":"Gr\u00eamio - RS","homeScore":"3","awayScore":"0","done":true},
{"homeTeam":"Am\u00e9rica Saf - MG","awayTeam":"Flamengo - RJ","homeScore":"0","awayScore":"3","done":true},
{"homeTeam":"S\u00e3o Paulo - SP","awayTeam":"Cuiab\u00e1 Saf - MT","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Internacional - RS","awayTeam":"Red Bull Bragantino - SP","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Fortaleza - CE","awayTeam":"Palmeiras - SP","homeScore":"2","awayScore":"2","done":true},
{"homeTeam":"Goi\u00e1s - GO","awayTeam":"Cruzeiro Saf - MG","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Vasco da Gama S.a.f. - RJ","awayTeam":"Corinthians - SP","homeScore":"2","awayScore":"4","done":true},
{"homeTeam":"Santos - SP","awayTeam":"Fluminense - RJ","homeScore":"0","awayScore":"3","done":true},
{"homeTeam":"Flamengo - RJ","awayTeam":"Atl\u00e9tico Mineiro Saf - MG","homeScore":"0","awayScore":"3","done":true},
{"homeTeam":"Cuiab\u00e1 Saf - MT","awayTeam":"Internacional - RS","homeScore":"0","awayScore":"2","done":true},
{"homeTeam":"Bahia - BA","awayTeam":"S\u00e3o Paulo - SP","homeScore":"0","awayScore":"1","done":true},
{"homeTeam":"Coritiba S.a.f. - PR","awayTeam":"Botafogo - RJ","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Palmeiras - SP","awayTeam":"Am\u00e9rica Saf - MG","homeScore":"4","awayScore":"0","done":true},
{"homeTeam":"Gr\u00eamio - RS","awayTeam":"Goi\u00e1s - GO","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Cruzeiro Saf - MG","awayTeam":"Athletico Paranaense - PR","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Red Bull Bragantino - SP","awayTeam":"Fortaleza - CE","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Corinthians - SP","awayTeam":"Internacional - RS","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Atl\u00e9tico Mineiro Saf - MG","awayTeam":"S\u00e3o Paulo - SP","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Flamengo - RJ","awayTeam":"Cuiab\u00e1 Saf - MT","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"Palmeiras - SP","awayTeam":"Fluminense - RJ","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Athletico Paranaense - PR","awayTeam":"Santos - SP","homeScore":"3","awayScore":"0","done":true},
{"homeTeam":"Am\u00e9rica Saf - MG","awayTeam":"Bahia - BA","homeScore":"3","awayScore":"2","done":true},
{"homeTeam":"Fortaleza - CE","awayTeam":"Goi\u00e1s - GO","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Gr\u00eamio - RS","awayTeam":"Vasco da Gama S.a.f. - RJ","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Red Bull Bragantino - SP","awayTeam":"Coritiba S.a.f. - PR","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Botafogo - RJ","awayTeam":"Cruzeiro Saf - MG","homeScore":"0","awayScore":"0","done":true},
{"homeTeam":"Goi\u00e1s - GO","awayTeam":"Am\u00e9rica Saf - MG","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Fluminense - RJ","awayTeam":"Gr\u00eamio - RS","homeScore":"2","awayScore":"3","done":true},
{"homeTeam":"Vasco da Gama S.a.f. - RJ","awayTeam":"Red Bull Bragantino - SP","homeScore":"2","awayScore":"1","done":true},
{"homeTeam":"S\u00e3o Paulo - SP","awayTeam":"Flamengo - RJ","homeScore":"1","awayScore":"0","done":true},
{"homeTeam":"Santos - SP","awayTeam":"Fortaleza - CE","homeScore":"1","awayScore":"2","done":true},
{"homeTeam":"Cruzeiro Saf - MG","awayTeam":"Palmeiras - SP","homeScore":"1","awayScore":"1","done":true},
{"homeTeam":"Internacional - RS","awayTeam":"Botafogo - RJ","homeScore":"3","awayScore":"1","done":true},
{"homeTeam":"Coritiba S.a.f. - PR","awayTeam":"Corinthians - SP","homeScore":"0","awayScore":"2","done":true},
{"homeTeam":"Bahia - BA","awayTeam":"Atl\u00e9tico Mineiro Saf - MG","homeScore":"4","awayScore":"1","done":true},
{"homeTeam":"Cuiab\u00e1 Saf - MT","awayTeam":"Athletico Paranaense - PR","homeScore":"3","awayScore":"0","done":true}];    
    let badgesDictionary = {"Palmeiras - SP":"https:\/\/conteudo.cbf.com.br\/cdn\/imagens\/escudos\/00019sp.jpg",
      "Cuiab\u00e1 Saf - MT":"https:\/\/conteudo.cbf.com.br\/cdn\/imagens\/escudos\/00062mt.jpg",
      "Am\u00e9rica Saf - MG":"https:\/\/conteudo.cbf.com.br\/cdn\/imagens\/escudos\/59897mg.jpg",
      "Fluminense - RJ":"https:\/\/conteudo.cbf.com.br\/cdn\/imagens\/escudos\/00009rj.jpg",
      "Botafogo - RJ":"https:\/\/conteudo.cbf.com.br\/cdn\/imagens\/escudos\/60175rj.jpg",
      "S\u00e3o Paulo - SP":"https:\/\/conteudo.cbf.com.br\/cdn\/imagens\/escudos\/00017sp.jpg",
      "Athletico Paranaense - PR":"https:\/\/conteudo.cbf.com.br\/cdn\/imagens\/escudos\/00004pr.jpg",
      "Goi\u00e1s - GO":"https:\/\/conteudo.cbf.com.br\/cdn\/imagens\/escudos\/00009go.jpg",
      "Red Bull Bragantino - SP":"https:\/\/conteudo.cbf.com.br\/cdn\/imagens\/escudos\/00006sp.jpg",
      "Bahia - BA":"https:\/\/conteudo.cbf.com.br\/cdn\/imagens\/escudos\/61377ba.jpg",
      "Fortaleza - CE":"https:\/\/conteudo.cbf.com.br\/cdn\/imagens\/escudos\/00003ce.jpg",
      "Internacional - RS":"https:\/\/conteudo.cbf.com.br\/cdn\/imagens\/escudos\/00009rs.jpg",
      "Atl\u00e9tico Mineiro Saf - MG":"https:\/\/conteudo.cbf.com.br\/cdn\/imagens\/escudos\/62194mg.jpg",
      "Vasco da Gama S.a.f. - RJ":"https:\/\/conteudo.cbf.com.br\/cdn\/imagens\/escudos\/60646rj.jpg",
      "Flamengo - RJ":"https:\/\/conteudo.cbf.com.br\/cdn\/imagens\/escudos\/00006rj.jpg",
      "Coritiba S.a.f. - PR":"https:\/\/conteudo.cbf.com.br\/cdn\/imagens\/escudos\/61590pr.jpg",
      "Corinthians - SP":"https:\/\/conteudo.cbf.com.br\/cdn\/imagens\/escudos\/00021sp.jpg",
      "Cruzeiro Saf - MG":"https:\/\/conteudo.cbf.com.br\/cdn\/imagens\/escudos\/59849mg.jpg",
      "Gr\u00eamio - RS":"https:\/\/conteudo.cbf.com.br\/cdn\/imagens\/escudos\/00008rs.jpg",
      "Santos - SP":"https:\/\/conteudo.cbf.com.br\/cdn\/imagens\/escudos\/00018sp.jpg"};    

function displayListOfMatches(listOfMatches) {
  let table = "<h2>Lista completa de jogos</h2><table border='1'><tr><th>#</th><th>Mandante</th><th></th><th>x</th><th></th><th>Visitante</th></tr>";
  listOfMatches.forEach((game, i) => {
    let homeBadge = badgesDictionary[game.homeTeam];
    let awayBadge = badgesDictionary[game.awayTeam];
    table += `<tr>
        <td>${i}</td>
        <td><img height='40' width='40' src='${homeBadge}' title='${game.homeTeam}'</img></td>
        <td id="homeScore_${i}">${game.homeScore}</td>
        <td>X</td>
        <td id="awayScore_${i}">${game.awayScore}</td>
        <td><img height='40' width='40' src='${awayBadge}' title='${game.awayTeam}'</img>
        <td><button class="editMatchButton" id="editButton_${i}">Editar</button></td>
    </tr>`;
  });
  table += "</table>";
  document.getElementById("divMatches").innerHTML = table;
  
//  for( button of  document.getElementsByClassName("editMatchButton") ) {
//    button.addEventListener('click', enableEditGame);
//  }
}


document.addEventListener('DOMContentLoaded', (event) => {
      displayListOfMatches(listOfMatches);
      document.querySelector("#menuButton")
        .addEventListener("click", (e) => {
          const panel = document.querySelector("#menuPanel");
          if (panel.classList.contains("left")) {
            panel.classList.remove("left");
          } else {
            panel.classList.add("left");
          }
        });
});


